name: vxport
description: Web Portfolio inspired by VSCode
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  blur: ^3.1.0
  flutter:
    sdk: flutter
  flutter_code_editor: ^0.2.9
  flutter_highlight: ^0.7.0
  flutter_riverpod: ^2.4.4
  google_fonts: ^6.1.0
  highlight: ^0.7.0
  just_the_tooltip: ^0.0.12
  lucide_icons: ^0.257.0
  markdown_widget: ^2.3.1
  package_info_plus: ^4.2.0
  resizable_widget: ^1.0.5
  themed: ^4.0.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
